### ISSUE TITLE
add QUIC as protocol using guidance from here

### ISSUE THREAD

**Issue by rscheff** [ietf-wg-ccwg/rfc5033bis#1]
at the time 5033 was written, only TCP, DCCP and SCTP were around, using CC; nowadays, many more protocols use CC - with QUIC standing out as a here, probably warranting it's explicit mentioning.

**Comment by huitema** [comment]
Yes. Note that there is a bit of sadness here, because QUIC was forced to describe use of Reno in RFC 9002, while most deployments use Cubic or BBR. But the WG could not go beyond Reno... because of RFC 5033!

**Comment by huitema** [comment]
This one seems simple, but is not. The introduction text says:
~~~
: Impact on Standard TCP, SCTP {{!RFC2960}}, and DCCP {{!RFC4340}}.
~~~
This formulation, "Impact on standard TCP", assumes that the congestion control algorithm is an integral part of the TCP specification. The situation has changed, and I think this part should be rewritten as:
~~~
: Impact on existing deployments of TCP,  SCTP {{!RFC2960}}, QUIC {{!RFC9000}} and DCCP {{!RFC4340}}.
~~~
The reference here should be RFC9000, the specification of the transport protocol, rather than RFC9002, the specification of default loss recovery and congestion control algorithms. And the text should then be modified to mention that our goal is to not wantonly disrupt existing deployments -- whether they use Reno, Cubic or BBR. The point is "don't disrupt the Internet", not "don't offend the pride of the IETF".
