### ISSUE TITLE
Non-standard algorithms

### ISSUE THREAD

**Issue by martinduke** [ietf-wg-ccwg/rfc5033bis#35]
The text currently reads:

"The community should also consider other non-standard congestion controls known to be widely deployed,"

This is a compromise to land a mostly unrelated PR.

@gorryfair doesn't think it's fair to expect participants to test algorithms that aren't fully specified.

I would argue that if such specifications exist and the algorithm is systemically important, it absolutely should be modeled. Moreover, if the algorithm is rather loosely described, in many cases there is open source code (often in a Linux fork!) that can be tested on a host, or in simulation frameworks like ns3.

If an algorithm is a true black box, with no description besides marketing material, and no open-source code, I agree there is not much to be done. I also believe that while algorithms like this exist, they are not systemically important to the internet.

**Comment by martinduke** [comment]
gorry: ns3 code is not super high fidelity.

**Comment by ekinnear** [comment]
Discussed at IETF 118: 
- There's a danger if you see a realtime flow that goes faster than a best effort flow, since realtime is usually constrained by other factors (potentially needing time to move forwards to generate more data)
- Seems hard to imagine that something not specified is able to place a burden on anybody else. If you want others to do a thing, write it down and document it. Of course, there is no protocol police: we cannot prevent people from deploying whatever they want. Can we provide a carrot for people to play by the rules: 
- Could be a SHOULD consider requirements and how to interact
- We have: 
    - Guidance for people who are writing specs that aren't yet part of the community
    - How do we evaluate those protocols
    - How do we ensure that fairness can exist with these
- Need to have a commitment from this WG to help and not just throw up new requirements for data and for those bringing new CCs to engage positively. Perhaps spelling this out clearly
- @martinduke to file issue to write something encouraging for people early on in the document
- Christian notes that separate queues between realtime and best effort are not actually a strong requirement
- To measure capacity you do need some sort of queue, or else you cannot measure
